config/routes.rb
Grouptable::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :secret_codes

   root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new # guest user (not logged in)
    role = Role.find_by_name('admin')
   if role.users.include?(user)
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  # attr_accessible :title, :body
  has_and_belongs_to_many :users, :join_table => :users_roles
end

app/models/secret_code.rb
class SecretCode < ActiveRecord::Base
   attr_accessible :user_id, :code
   belongs_to :user

def self.get_for_signup(code)
  find(:first, :conditions => ["code =? and (user_id is null or user_id = 0)", code])
end
end
  

app/models/user.rb
class User < ActiveRecord::Base
  set_table_name "user_lists"
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first,:last,:is_admin
  # attr_accessible :title, :body
  
  has_one :secret_code
  accepts_nested_attributes_for :secret_code
  
  def self.create_user_with_secret_code(user_params,secret_code)
    
    User.transaction do
      user = User.create!(user_params)
      secret_code.update_attributes(:user_id => user.id)
    end
  return self
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  


  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
   
  def create  
  secret_code = SecretCode.get_for_signup(params[:secret_code][:code])  
  if secret_code          
      User.create_user_with_secret_code(params[:user], secret_code) 
      redirect_to root_path
   else
    flash[:notice] = "Invalid secret Code"
    render :action => "new"
  end 
  end  
end

app/controllers/secret_codes_controller.rb
class SecretCodesController < ApplicationController
 layout "application"
 load_and_authorize_resource
def index
  @codes = SecretCode.all  
end
  

def create
  if params[:value]
    (1..params[:value].to_i).each do |code|
      secret_code = (0..6).map{ rand(36).to_s(36) }.join
     status =  SecretCode.create!(:code => secret_code) && status
     if status 
       redirect_to :action => "index"
     else
       flash[:notice] = "Generated Successfully"
       render :action => "index"
     end
    end
  else
    flash[:notice] = "Please select value"  
    render :action => "index"
  end 
  
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/secret_codes_helper.rb
module SecretCodesHelper
end

app/views/home/index.html.erb
WELCOME

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grouptable</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
		<%= link_to "Secret Codes", secret_codes_path %>
		
	
	<div style='float: right'>
	<% if user_signed_in? %>
        Signed in as <%= current_user.email %>. This cannot be cheese?
        <%= link_to 'Sign out', destroy_user_session_path, :method=> :delete %>
    <% else %>
        <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
    <% end %>
</div>

<div>
	<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
</div>
<%= yield %>

</body>
</html>

app/views/secret_codes/_form.html.erb
<%= form_tag :action => "create" do %>
<%#= select_tag 'value','for', [['1','1'],['10', '10'], ['20', '20'], ['50','50'],['100','100']] %>
<%= select_tag "value", options_for_select(%w{ 1 10 20 50 100  }), :default => "10" %>
<%= submit_tag "Generate"%>
<% end %>

app/views/secret_codes/index.html.erb
<p> Secret Codes: </p>

<%= render :partial =>"form"%>

<table class="table table-striped">
	<thead>
		<th> S.No </th>
		<th> Secret Code</th>
		<th> User</th>
		
	</thead>
	<% count = 1%>
	<%@secret_codes.each do |code|%>
		<tr>
			<td><%= count %></td>
			<td>
				<%=code.code%>
			</td>
			<td><%= code.user ? code.user.first : "-"%></td>
		</tr>
		<%count +=1 %>
	<% end %>
</table>